### ISSUE TITLE
Can you please make the "Thumb Up" icon more visible ?

### ISSUE THREAD

**Issue by LL25255252** [aleck07/youtube#1]
As of now it is too dark when it's ON and too dark when it's OFF.
Thanks in advance.

**Comment by aleck07** [comment]
Sorry for seeing this so late. What theme are you using and can you please provide a screenshot? I use the rose pine (not dawn or moon) and I'm not experiencing this. Thanks.

**Comment by ahloiscreamo** [comment]
Hello!

I have the same problem, the latest youtube update broke many thing such as sub button, thumbs etc etc, i'm using rose pine moon version.

![Screenshot from 2023-02-13 07-14-52](https://user-images.githubusercontent.com/9318372/218343226-f8f9bb50-6c06-4fa3-b6df-b8baf831a746.png)

**Comment by aleck07** [comment]
Sorry for fixing this so late. It should hopefully be fixed now, just update it on your end.

**Comment by ahloiscreamo** [comment]
Hello, i think it happened again in the recent update
![Screenshot from 2023-09-12 23-25-48](https://github.com/artilate/youtube/assets/9318372/1acde92f-a03f-4d5f-a3f9-4ad0d90ed3e1)
so the theme only work when youtube using light interface, sometimes it load sometimes not, maybe because i use Stylus to activated the theme.

**Comment by ahloiscreamo** [comment]
welp, i just reinstall and everything back to normal now. problem solved~
